### ISSUE TITLE
发送模板消息报空指针问题

### ISSUE THREAD

**Issue by leeue14** [binarywang/weixin-java-mp-demo-springboot#43]
我用了你这个例子写了一个发送消息模版的方法，报空指针 获取MultiConfigStorages时候为空，因为你默认的键是default。是WxMpConfiguration里面要改什么吗？
，java.lang.NullPointerException: null
at me.chanjar.weixin.mp.api.impl.WxMpServiceHttpClientImpl.getAccessToken(WxMpServiceHttpClientImpl.java:66) ~[weixin-java-mp-3.3.7.B.jar:na]
at me.chanjar.weixin.mp.api.impl.BaseWxMpServiceImpl.executeInternal(BaseWxMpServiceImpl.java:299) ~[weixin-java-mp-3.3.7.B.jar:na]
at me.chanjar.weixin.mp.api.impl.BaseWxMpServiceImpl.execute(BaseWxMpServiceImpl.java:264) ~[weixin-java-mp-3.3.7.B.jar:na]
at me.chanjar.weixin.mp.api.impl.BaseWxMpServiceImpl.post(BaseWxMpServiceImpl.java:253) ~[weixin-java-mp-3.3.7.B.jar:na]
at me.chanjar.weixin.mp.api.impl.WxMpTemplateMsgServiceImpl.sendTemplateMsg(WxMpTemplateMsgServiceImpl.java:36) ~[weixin-java-mp-3.3.7.B.jar:na]

**Comment by binarywang** [comment]
请参考`com.github.binarywang.demo.wx.mp.controller.WxMenuController`的部分代码

**Comment by leeue14** [comment]
好的，我以为跟原来差不多方式，感谢

**Comment by binarywang** [comment]
不过感谢提出这个问题，可以考虑做个兼容，保证原有但公众号情况下代码不用发生改变。

**Comment by binarywang** [comment]
楼主可以更新代码，使用最新版本的sdk，看是否还有同样问题，或者还有没有其他问题，欢迎及时提出
