### ISSUE TITLE
多公众号报错

### ISSUE THREAD

**Issue by qhl100** [binarywang/weixin-java-mp-demo-springboot#81]
java.lang.NullPointerException: null
	at me.chanjar.weixin.mp.enums.WxMpApiUrl$Other.getUrl(WxMpApiUrl.java:139)
	at me.chanjar.weixin.mp.api.impl.BaseWxMpServiceImpl.oauth2getAccessToken(BaseWxMpServiceImpl.java:194)

config 为 空

    @Override
    public String getUrl(WxMpConfigStorage config) {
      return buildUrl(config.getHostConfig(), prefix, path);
    }

**Comment by binarywang** [comment]
那是因为你config确实为null了吧，检查下为什么
